services:
  mysql:
    image: mysql:8.0
    container_name: myquotes-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myquotes_db
      MYSQL_USER: myquotes_user
      MYSQL_PASSWORD: myquotes_pass
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 